/**
 * Utility function to conditionally join class names together.
 * Useful for Tailwind CSS classes.
 */
export function cn(...classes: (string | undefined | null | false)[]) {
  return classes.filter(Boolean).join(" ");
}

/**
 * Represents a single step in an Agent's thinking process.
 */
export type AgentStep = {
  id: string;
  title: string;
  status: 'pending' | 'running' | 'success' | 'error';
  details?: string;
};

/**
 * Represents a file attachment uploaded by the user.
 */
export type Attachment = {
  id: string;
  name: string;
  type: string;
  data: string; // base64 data URL
};

/**
 * Represents a single message in a conversation.
 * Can include attachments, agent steps, and RAG sources.
 */
export type Message = {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp: number;
  steps?: AgentStep[];
  attachments?: Attachment[];
  sources?: { id: string; docName: string; text: string; score: number }[];
  confidence?: number;
};

/**
 * Represents a complete chat conversation.
 */
export type Conversation = {
  id: string;
  title: string;
  messages: Message[];
  updatedAt: number;
};

/**
 * Represents a single MCP tool entry configurable by the user.
 */
export type McpTool = {
  id: string;
  label: string;
  url: string;
};

/**
 * Global application configuration settings.
 */
export type AppConfig = {
  provider: 'openai' | 'ollama';
  baseUrl: string;
  apiKey: string;
  model: string;
  systemPrompt: string;
  elasticsearchUrl: string;
  elasticsearchIndex: string;
  elasticsearchUsername: string;
  elasticsearchPassword: string;
  embeddingBaseUrl: string;
  embeddingApiKey: string;
  embeddingModel: string;
  embeddingVerifySsl: boolean;
  chunkSize: number;
  chunkOverlap: number;
  knnNeighbors: number;
  mcpTools: McpTool[];
};

/**
 * Default configuration values used when the app first loads.
 */
export const DEFAULT_CONFIG: AppConfig = {
  provider: 'ollama',
  baseUrl: "http://localhost:11434",
  apiKey: "",
  model: "llama3",
  systemPrompt: "You are a helpful, smart, and concise AI assistant. Format your responses beautifully using markdown. When offering choices, use markdown task lists (- [ ] Option).",
  elasticsearchUrl: "http://localhost:9200",
  elasticsearchIndex: "rag_documents",
  elasticsearchUsername: "",
  elasticsearchPassword: "",
  embeddingBaseUrl: "http://localhost:11434/v1",
  embeddingApiKey: "",
  embeddingModel: "nomic-embed-text",
  embeddingVerifySsl: true,
  chunkSize: 512,
  chunkOverlap: 50,
  knnNeighbors: 50,
  mcpTools: [
    { id: 'mcp_1', label: 'MCP Tool 1', url: '' },
    { id: 'mcp_2', label: 'MCP Tool 2', url: '' },
  ],
};

/**
 * Preprocesses markdown text before it is rendered by ReactMarkdown.
 * This function fixes common formatting issues, such as inline task lists
 * generated by some LLMs that don't include proper line breaks.
 */
export function preprocessMarkdown(md: string): string {
  if (!md) return '';
  let text = md;
  // Fix inline task list items generated by some LLMs
  text = text.replace(/([^\n])\s+([-*]\s+\[[ xX]\]\s+)/g, '$1\n$2');
  // Fix inline normal list items (only if preceded by punctuation to avoid matching "A - B")
  text = text.replace(/([.!?])\s+([-*]\s+[A-Z0-9])/g, '$1\n$2');
  // Fix inline numbered list items
  text = text.replace(/([.!?])\s+(\d+\.\s+[A-Z0-9])/g, '$1\n$2');
  return text;
}

/**
 * Legacy function to parse markdown to HTML.
 * Note: This is largely superseded by ReactMarkdown in the ChatMessage component,
 * but may still be used in older parts of the codebase if any remain.
 */
export function parseMarkdownToHTML(md: string): string {
  if (!md) return '';
  
  let html = md;
  
  // Fix inline task list items generated by some LLMs
  html = html.replace(/([^\n])\s+([-*]\s+\[[ xX]\]\s+)/g, '$1\n$2');
  // Fix inline normal list items (only if preceded by punctuation to avoid matching "A - B")
  html = html.replace(/([.!?])\s+([-*]\s+[A-Z0-9])/g, '$1\n$2');
  // Fix inline numbered list items
  html = html.replace(/([.!?])\s+(\d+\.\s+[A-Z0-9])/g, '$1\n$2');

  // Escape HTML to prevent XSS, but allow <u> and <ins>
  html = html.replace(/</g, '&lt;').replace(/>/g, '&gt;');
  html = html.replace(/&lt;u&gt;(.*?)&lt;\/u&gt;/g, '<u>$1</u>');
  html = html.replace(/&lt;ins&gt;(.*?)&lt;\/ins&gt;/g, '<ins>$1</ins>');

  // Code blocks
  html = html.replace(/```[\s\S]*?\n([\s\S]*?)```/g, '<pre><code>$1</code></pre>');
  
  // Inline code
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Bold & Italic
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

  // Links
  html = html.replace(/\[(.*?)\]\((.*?)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');

  // Process blocks
  const blocks = html.split(/\n\n+/);
  const processedBlocks = blocks.map(block => {
    if (block.match(/^### (.*$)/im)) return block.replace(/^### (.*$)/gim, '<h3>$1</h3>');
    if (block.match(/^## (.*$)/im)) return block.replace(/^## (.*$)/gim, '<h2>$1</h2>');
    if (block.match(/^# (.*$)/im)) return block.replace(/^# (.*$)/gim, '<h1>$1</h1>');
    if (block.match(/^\> /im)) return block.replace(/^\> (.*$)/gim, '<blockquote>$1</blockquote>');

    if (block.match(/^([-*]|\d+\.)\s+/im)) {
      const lines = block.split('\n');
      let resultHtml = '';
      let listType = ''; // 'ul' or 'ol'

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (!line.trim()) continue;

        const isTaskEmpty = line.match(/^[-*]\s+\[ \]\s+(.*$)/);
        const isTaskChecked = line.match(/^[-*]\s+\[[xX]\]\s+(.*$)/);
        const isNormalList = line.match(/^[-*]\s+(.*$)/);
        const isNumberedList = line.match(/^(\d+)\.\s+(.*$)/);

        if (isTaskEmpty || isTaskChecked || isNormalList || isNumberedList) {
          const currentType = isNumberedList ? 'ol' : 'ul';
          if (listType !== currentType) {
            if (listType) resultHtml += `</${listType}>`;
            resultHtml += `<${currentType}>`;
            listType = currentType;
          }
          
          if (isTaskEmpty) {
            resultHtml += `<li class="task-list-item" data-task="${isTaskEmpty[1]}"><input type="checkbox" /> <span>${isTaskEmpty[1]}</span></li>`;
          } else if (isTaskChecked) {
            resultHtml += `<li class="task-list-item" data-task="${isTaskChecked[1]}"><input type="checkbox" checked /> <span>${isTaskChecked[1]}</span></li>`;
          } else if (isNormalList) {
            resultHtml += `<li>${isNormalList[1]}</li>`;
          } else if (isNumberedList) {
            resultHtml += `<li>${isNumberedList[2]}</li>`;
          }
        } else {
          if (listType) {
            resultHtml += `</${listType}>`;
            listType = '';
          }
          resultHtml += `<p>${line}</p>`;
        }
      }
      if (listType) {
        resultHtml += `</${listType}>`;
      }
      return resultHtml;
    }

    if (block.match(/^\|.*\|$/m)) {
      const lines = block.split('\n').filter(line => line.trim().startsWith('|'));
      if (lines.length >= 2) {
        let tableHtml = '<div class="overflow-x-auto my-4"><table class="min-w-full divide-y divide-gray-200 border border-gray-200 rounded-lg shadow-sm">';
        
        // Parse header
        const headerCells = lines[0].split('|').slice(1, -1).map(c => c.trim());
        tableHtml += '<thead class="bg-gray-50/80"><tr>';
        headerCells.forEach(cell => {
          tableHtml += `<th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider border-b border-gray-200">${cell}</th>`;
        });
        tableHtml += '</tr></thead>';

        // Parse body
        tableHtml += '<tbody class="bg-white divide-y divide-gray-100">';
        for (let i = 2; i < lines.length; i++) {
          const cells = lines[i].split('|').slice(1, -1).map(c => c.trim());
          tableHtml += '<tr class="hover:bg-gray-50/50 transition-colors">';
          cells.forEach(cell => {
            tableHtml += `<td class="px-4 py-3 text-sm text-gray-700">${cell}</td>`;
          });
          tableHtml += '</tr>';
        }
        tableHtml += '</tbody></table></div>';
        return tableHtml;
      }
    }

    if (block.startsWith('<pre>')) return block;

    return `<p>${block.replace(/\n/g, '<br/>')}</p>`;
  });

  return processedBlocks.join('');
}
